### PR TITLE
Update to Python 3

### PR DESCRIPTION
**Pull request by IFcoltransG**
Python 2 no longer has official support. This patch should fix `poesy` to be compatible with Python 3, and also update dependencies to their latest versions at time of writing.

### CODE REVIEW

**Comment by quadrismegistus** [comment]
Thanks for this @IFcoltransG! Let me know if you think this is ready to merge?

**Comment by IFcoltransG** [comment]
> Thanks for this @IFcoltransG! Let me know if you think this is ready to merge?

No problem. I think this pull request is ready, although I'll probably create a second pull request later today which would let you configure prosodic by setting values in a dictionary within poesy.  (It would make the workaround in #3 simpler.)

**Comment by IFcoltransG** [comment]
This pull request for updating the code to Python 3 is done. Once it's merged, I'll make a separate request re the config dictionary.

**Comment by quadrismegistus** [comment]
Woohoo! Thanks again!!

**Pull request merged**
